services:
  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/data:/prometheus
    restart: always
    networks:
      - monitoring

  loki:
    container_name: loki
    image: grafana/loki:2.9.2
    volumes:
      - ./loki/loki-config.yaml:/etc/loki/local-config.yaml
      - ./loki/data:/loki
    command: -config.file=/etc/loki/local-config.yaml
    restart: always
    networks:
      - monitoring

networks:
  monitoring:
    name: monitoring
    driver: bridge
